### ISSUE TITLE
[FEATURE] Validar que se encontró la palabra

### ISSUE THREAD

**Issue by MelinaLoscalzo** [CeciJurgens/Aninfo---TP-Sopa-de-Letras#20]
## 🚀 Feature

Cuando un jugador toque una serie de casillas en el tablero, se debe validar que esta sea una palabra que está buscando. 

### Motivation

Validar las palabras es fundamente para determinar si el jugador ha encontrado una palabra en el tablero, lo cual es el objetivo del juego.

### Implementation

Se cuenta con la clase Tablero, Palabra y Casillero. Cuando un jugador clickea una serie de casilleros (que conforman el tablero), esto se traduce en una serie de coordenadas. A su vez, las Palabras al ubicarse en el tablero cuando se crea el juego, se les atribuye una ubicacion (coordenadas). Para saber si la palabra es encontrada, hay que comparar si las coordenadas que clickeo el usuario concuerdan con la ubicacion de la palabra.

**Comment by ppazb** [comment]
Posible implementacion: En vez de validar la secuencia (que podria traer problemas a la hora de palabras q contengan otras palabras (ej: si marca amoroso y esta amor ambas se marcan como encontradas por mas q no van a estar en el mismo lugar) podriamos tener que cada vez q se genera un tablero, cada palabra sabe en q posicion esta ubicada y se guarda la lista de casilleros (ej: coordenadas), despues es solo checkear q las cordenadas seleccionadas por el jugador son exactamente las mismas (si el array de coordenadas es igual, significa q selecciono los casilleros correctos y encontro la palabra)
