### ISSUE TITLE
[FEATURE] Finalizo partida cuando jugador gana 

### ISSUE THREAD

**Issue by CeciJurgens** [CeciJurgens/Aninfo---TP-Sopa-de-Letras#26]
## 🚀 Feature

Finalizo partida cuando jugador gana

### Motivation

El usuario debe saber cuando gana la partida y cuantas palabras le falta para terminar el juego. El juego se termina cuando encuentra todas las palabras del tablero dentro del límite del tiempo

### Implementation

Una vez encontradas las palabras que forman parte del juego, el usuario debe saber que gano la partida.  Todas las palabras deben haber cambiado de estado  de noEncontrada a Encontrada y debería finalizarse la partida.

**Comment by Jsf-MK-ian** [comment]
Alternativa respecto a la duración del juego en el [FEATURE #14]
