### ISSUE TITLE
[FEATURE] Juego debe contar con un límite de tiempo de duración

### ISSUE THREAD

**Issue by Jsf-MK-ian** [CeciJurgens/Aninfo---TP-Sopa-de-Letras#30]
Juego debe contar con un límite de tiempo de duración

## Motivation:

El Juego debe definir un límite de duración. 

## Implementation:

El juego contará con un temporizador con el cual se definirá su duración. Dicha duración se settea según cantidad y longitud de palabras a encontrar. El jugador perderá el juego si se acaba el tiempo sin haber encontrado todas las palabras.

Si la palabra es corta, es mas dificil de encontrar y por ende tendria mas tiempo
Si la palabra es larga, es mas facil de encontrar y por ende tendria menos tiempo

**Comment by CeciJurgens** [comment]
https://docs.oracle.com/javase/8/docs/api/java/util/Timer.html
