### ISSUE TITLE
[FEATURE ] Mostrar en pantalla temporizador de la duración del juego

### ISSUE THREAD

**Issue by Jsf-MK-ian** [CeciJurgens/Aninfo---TP-Sopa-de-Letras#31]
Mostrar en pantalla temporizador de la duración del juego

## Motivation:

Se debe mostrar en pantalla un temporizador que indique la duración del juego. Durante el juego el jugador va a poder saber el tiempo con el que cuenta para encontrar todas las palabras.

## Implementation:

Cuando el jugador inicialice el juego , el temporizador va a empezar a correr en pantalla y frenará al alcanzar su límite. Dicho límite ya estará definido previamente según cantidad y longitud de palabras.

**Comment by CeciJurgens** [comment]
La dificultad:
- Si la palabra es corta, es mas dificil de encontrar y por ende tendria mas tiempo 
- Si la palabra es larga, es mas facil de encontrar y por ende tendria menos tiempo
